import * as images from '../assets/index';

export const goods = [
  {
    id: '01',
    name: 'Brielle Necklace',
    img: images.urlImg,
    collection: 'Holiday',
    category: 'necklace',
    metal: 'gold',
    rating: '5',
    color: 'multicolor',
    bestsellers: 'true',
    year: 2018,
    price: 155.0,
    stock: 5,
    description:
      'A gorgeously stunning collar necklace perfect for accompanying you on all of your colorful ventures. Shine bright with glimmering hues of blush, refreshing tones of green, and feminine pops of pearl. A combination sure to leave you with everlasting memories.',
  },
  {
    id: '02',
    name: 'Drew Pendant',
    img: images.urlImg2,
    collection: 'Pearls',
    category: 'necklace',
    metal: 'gold',
    rating: '3',
    color: 'pearl',
    bestsellers: 'false',
    year: 2022,
    price: 55.0,
    stock: 4,
    description:
      'Introducing your new favorite piece - a classic pendant featuring a luminous freshwater pearl on a beautifully delicate chain. An effortless way to add a sophisticated vibe to your outfit.',
  },
  {
    id: '03',
    name: 'Pallas Drops',
    img: images.urlImg3,
    collection: 'Luxe',
    category: 'earrings',
    metal: 'gold',
    rating: '3',
    color: 'clear',
    bestsellers: 'false',
    year: 2019,
    price: 90.0,
    stock: 15,
    description:
      "Crystal gems come together in this beautiful floral silhouette earring. The perfect dose of glam for that finishing touch you've been searching for. Pair with a cocktail dress or go business casual with these - the options are endless!",
  },
  {
    id: '04',
    name: 'Luna Studs',
    img: images.urlImg4,
    collection: 'Pearls',
    category: 'earrings',
    metal: 'gold',
    rating: '2',
    color: 'pearl',
    bestsellers: 'true',
    year: 2022,
    price: 75.0,
    stock: 6,
    description:
      'This classic stud earring has the perfect amount of sparkle - outfit your entire bridal party or let this stud shine centre stage. Designed in a timeless and elevated style - just like the bride herself!',
  },
  {
    id: '05',
    name: 'Layla Bracelet',
    img: images.urlImg5,
    collection: 'Holiday',
    category: 'bracelet',
    metal: 'gold',
    rating: '2',
    color: 'multicolor',
    bestsellers: 'true',
    year: 2021,
    price: 105.0,
    stock: 7,
    description:
      'Feminine and elegant, this luxe bracelet brings together an elevated pattern of crystals with compliments of gorgeous blush and green tones. The perfect dangling adornment for your wrist. Wear on its own or layer with other dainty bracelets.',
  },
  {
    id: '06',
    name: 'Nigella Bracelet',
    img: images.urlImg6,
    collection: 'Pearls',
    category: 'bracelet',
    metal: 'silver',
    rating: '1',
    color: 'clear',
    bestsellers: 'false',
    year: 2021,
    price: 65.0,
    stock: 2,
    description:
      "A luxe bracelet adorned with pearls and crystals. Complete your look with effortless sophistication, and don't be afraid to layer with other delicate bracelets.",
  },
  {
    id: '07',
    name: 'Everly Cuff',
    img: images.urlImg7,
    collection: 'Everyday',
    category: 'bracelet',
    metal: 'silver',
    rating: '1',
    color: 'clear',
    bestsellers: 'false',
    year: 2022,
    price: 60.0,
    stock: 4,
    description:
      'A cuff bracelet tipped with stunning crystal elements. The mix of modern style and vintage charm will make you want to wear it non-stop. Adjust to fit on your wrist, or higher up along your arm.',
  },
  {
    id: '08',
    name: 'Neveah Bracelet',
    img: images.urlImg8,
    collection: 'Pearls',
    category: 'bracelet',
    metal: 'silver',
    rating: '4',
    color: 'pearl',
    bestsellers: 'false',
    year: 2018,
    price: 62.0,
    stock: 3,
    description:
      "Elevate your look with bright pearls and delicate crystals. Suitable for all your looks and quick to become a favorite, you'll be wrapping luxe around your wrist over and over again.",
  },
  {
    id: '09',
    name: 'Archer Pendant',
    img: images.urlImg9,
    collection: 'Pearls',
    category: 'necklace',
    metal: 'gold',
    rating: '3',
    color: 'pearl',
    bestsellers: 'false',
    year: 2019,
    price: 45.0,
    stock: 9,
    description:
      "An elegant and sweet necklace you'll reach for day after day. Also makes a perfect keepsake for a bride to gift to her bridesmaids. Add this pearl necklace to your ensemble for a timeless vibe, or layer it with other necklaces for a chic look.",
  },
  {
    id: '10',
    name: 'Mina Hoops',
    img: images.urlImg10,
    collection: 'Everyday',
    category: 'earrings',
    metal: 'silver',
    rating: '4',
    color: 'clear',
    bestsellers: 'true',
    year: 2020,
    price: 64.0,
    stock: 7,
    description:
      'Classic hoop earrings with added luxe. These dainty hoops are designed with all the little details, featuring two rows of pave - inside and out - so you can shine from every angle.',
  },
  {
    id: '11',
    name: 'Thea Drops',
    img: images.urlImg11,
    collection: 'Holiday',
    category: 'earrings',
    metal: 'gold',
    rating: '4',
    color: 'multicolor',
    bestsellers: 'true',
    year: 2021,
    price: 72.0,
    stock: 12,
    description:
      'A classic and simple silhouette complimented by a harmonious color palette. Pops of pink and green are sure to add a touch of luxe to your look. Dress them up for an elegant evening, or keep it neutral and let their natural beauty shine.',
  },
  {
    id: '12',
    name: 'Porter Earrings',
    img: images.urlImg12,
    collection: 'Florals',
    category: 'earrings',
    metal: 'gold',
    rating: '5',
    color: 'multicolor',
    bestsellers: 'true',
    year: 2020,
    price: 172.0,
    stock: 11,
    description:
      'Say hello to our beautiful Porter Earrings in a gorgeous rich palette. With sophisticated colors and hints of berry tones, this stunning earring has an edgy and glamorous silhouette that perfectly frames your face and elevates your look.',
  },
  {
    id: '13',
    name: 'Monroe Stud Set',
    img: images.urlImg13,
    collection: 'Pearls',
    category: 'earrings',
    metal: 'gold',
    rating: '4',
    color: 'multicolor',
    bestsellers: 'true',
    year: 2019,
    price: 152.0,
    stock: 14,
    description:
      'Get the best of both worlds with a petite stud set that lets you be both feminine and subtly bold! Featuring an elevated palette and a combination of pearls and crystals, styling options with this set are oh-so-glamorous, and even better - endless.',
  },
  {
    id: '14',
    name: 'Andes Bracelet',
    img: images.urlImg14,
    collection: 'Luxe',
    category: 'bracelet',
    metal: 'gold',
    rating: '5',
    color: 'clear',
    bestsellers: 'true',
    year: 2022,
    price: 162.0,
    stock: 5,
    description:
      'We love a bracelet that goes with everything! This dainty bracelet is a classic and timeless piece, crafted with a luxe blend of alternating crystals for a touch of shine. This bracelet is thinner than our other statement bracelets and can be paired to create a layered look.',
  },
  {
    id: '15',
    name: 'Ritchie Bracelet',
    img: images.urlImg15,
    collection: 'Florals',
    category: 'bracelet',
    metal: 'gold',
    rating: '4',
    color: 'multicolor',
    bestsellers: 'true',
    year: 2018,
    price: 110.0,
    stock: 6,
    description:
      'A gorgeous delicate bracelet featuring a deep romantic palette and a playful mix of gems. Sophisticated, stylish, and charming.',
  },
  {
    id: '16',
    name: 'Maddie Hoops',
    img: images.urlImg16,
    collection: 'Everyday',
    category: 'earrings',
    metal: 'gold',
    rating: '4',
    color: 'clear',
    bestsellers: 'false',
    year: 2018,
    price: 50.0,
    stock: 20,
    description:
      'Dress up your lobes with luminous hoops that have an added touch of luxe. Shapes of pave keep this pair classic, fresh, and you shining bright.',
  },
  {
    id: '17',
    name: 'Crystal Necklace',
    img: images.urlImg17,
    collection: 'Luxe',
    category: 'necklace',
    metal: 'silver',
    rating: '4',
    color: 'clear',
    bestsellers: 'false',
    year: 2019,
    price: 63.0,
    stock: 12,
    description:
      "This beautiful and slim collar necklace features shiny gems in an alternating silhouette for a luxe but approachable look you'll love.",
  },
  {
    id: '18',
    name: 'Mini Heart',
    img: images.urlImg18,
    collection: 'Everyday',
    category: 'necklace',
    metal: 'silver',
    rating: '1',
    color: 'clear',
    bestsellers: 'true',
    year: 2020,
    price: 60.0,
    stock: 11,
    description:
      'The limited-edition Mini Heart necklace features a delicate and ever-so-dainty heart pendant. Our favorite way to wear our heart on our sleeve, and perfect for gifting to a loved one, a friend, or just for you!',
  },
  {
    id: '19',
    name: 'Essie Pendant',
    img: images.urlImg19,
    collection: 'Everyday',
    category: 'necklace',
    metal: 'silver',
    rating: '2',
    color: 'clear',
    bestsellers: 'true',
    year: 2021,
    price: 65.0,
    stock: 9,
    description:
      'Barely there, yet definitely there. A mini and dainty cluster of crystals on a delicate chain adorns your neckline with just a tiny amount of shine.',
  },
  {
    id: '20',
    name: 'Nomi Layered',
    img: images.urlImg20,
    collection: 'Everyday',
    category: 'necklace',
    metal: 'silver',
    rating: '2',
    color: 'clear',
    bestsellers: 'false',
    year: 2018,
    price: 55.0,
    stock: 14,
    description:
      "Double the luxe, double the sparkle. No need to stress about creating that layered look, because we've got it right here with the Nomi Pendant.",
  },
];
